# Generated by Django 4.2.30 on 2026-07-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brandbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='net_quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
