# Generated by Django 4.2.30 on 2026-07-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_herobanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='is_deal_of_the_day',
            field=models.BooleanField(default=False),
        ),
    ]
