# Generated by Django 4.2.30 on 2026-07-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
