# Generated by Django 4.2.30 on 2026-07-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_herobanner_is_active'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='herobanner',
            index=models.Index(fields=['is_active', 'sort_order'], name='products_he_is_acti_4ce801_idx'),
        ),
    ]
