# Generated by Django 4.2.30 on 2026-06-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
